# https://github.com/traefik/traefik/issues/9945#issuecomment-1590229681
# https://doc.traefik.io/traefik/reference/routing-configuration/http/tls/tls-certificates/#strict-sni-checking
# https://www.ssllabs.com/ssltest/
tls:
  options:
    default:
      sniStrict: true            # <-----  Strict SNI Checking
    #  minVersion: VersionTLS12
    #  cipherSuites:
    #    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
    #    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305  # TLS 1.2
    #    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
    #    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
    #    - TLS_AES_256_GCM_SHA384                  # TLS 1.3
    #    - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
    #    - TLS_FALLBACK_SCSV                       # TLS FALLBACK
    #  curvePreferences:
    #    - secp521r1
    #    - secp384r1
    #modern:
    #  minVersion: VersionTLS13